##############################
# Configurações Padrão
##############################
common: &common
  adapter: postgresql
  username: user_psql
  password: 123456
  host: localhost
  encode: utf8
  database: denuncie_ufba_dev # Necessário para o Guard + DatabaseCleaner

development:
  <<: *common
  database: denuncie_ufba_dev

production:
  adapter: postgresql
  username: user_psql
  password: 123456
  encode: utf8
  database: denuncia_ufba_production # Necessário para o Guard + DatabaseCleaner

test: &test
  <<: *common
  database: denuncia_ufba_test
